
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - fullstack-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - fullstack-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: on-failure
    env_file: ./.env
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
       "spring.datasource.url"  : "jdbc:mysql://mysql-db:3306/basic_tutorial?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC",
       "spring.datasource.username" : "root",
       "spring.datasource.password" : "Giovanna2025",
       "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
       "spring.jpa.hibernate.ddl-auto" : "update",
       "spring.jpa.show-sql" : true,
       "spring.jpa.properties.hibernate.format_sql" : true,
       "spring.jpa.generate-ddl" : true}'
     
    depends_on:
      - mysql-db
    networks:
      - fullstack-network

networks:
  fullstack-network:

volumes:
  mysql-data:
