name: Fullstack CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Fullstack (Maven + Angular)
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup Node.js for Angular frontend
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Build Angular frontend
      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build -- --configuration=production

      # Setup Java for Maven backend
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build Spring Boot backend
      - name: Build Backend
        working-directory: ./backend
        run: mvn clean install -DskipTests

      # (Optional) Run tests
      - name: Run Backend Tests
        working-directory: ./backend
        run: mvn test
